<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LDPL-MAC-V7YHH6Y6L7.local" failures="0" tests="2" name="Test 1" time="0.353" errors="0" timestamp="2025-03-06T11:07:44 IST">
  <testcase classname="BaseClass.BaseClass" name="@BeforeClass login" time="0.339">
    <failure type="org.openqa.selenium.SessionNotCreatedException" message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &amp;apos;LDPL-MAC-V7YHH6Y6L7.local&amp;apos;, ip: &amp;apos;fe80:0:0:0:1c69:e0ab:22ab:7304%en0&amp;apos;">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'LDPL-MAC-V7YHH6Y6L7.local', ip: 'fe80:0:0:0:1c69:e0ab:22ab:7304%en0'
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:536)
at io.appium.java_client.AppiumDriver.startSession(AppiumDriver.java:229)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:159)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:80)
at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:92)
at utility.Driver.launchAndroidApplication(Driver.java:46)
at BaseClass.BaseClass.login(BaseClass.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.openqa.selenium.WebDriverException: Connection refused
Build info: version: '4.11.0', revision: '040bc5406b'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '15.1.1', java.version: '17.0.9'
Driver info: driver.version: Driver
at io.appium.java_client.remote.AppiumCommandExecutor.lambda$execute$4(AppiumCommandExecutor.java:274)
at java.base/java.util.Optional.orElseGet(Optional.java:364)
at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:273)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:518)
... 36 more
Caused by: java.net.ConnectException: Connection refused
at java.base/sun.nio.ch.Net.pollConnect(Native Method)
at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass login -->
  <testcase classname="BaseClass.BaseClass" name="@AfterMethod attachScreenshot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod attachScreenshot -->
  <testcase classname="BaseClass.BaseClass" name="@AfterMethod attachScreenshot" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterMethod attachScreenshot -->
  <testcase classname="BaseClass.BaseClass" name="@AfterClass tearDown" time="0.0">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="test.Verify_Login_Scenarios" name="verify_login" time="0.0">
    <skipped/>
  </testcase> <!-- verify_login -->
  <testcase classname="test.Verify_Login_Scenarios" name="verify_logout" time="0.0">
    <skipped/>
  </testcase> <!-- verify_logout -->
</testsuite> <!-- Test 1 -->
